---
- name: Adiciona a chave GPG
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key

- name: Adiciona o repositorio
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable 
    state: present
    update_cache: yes

- name: Instala o docker-ce
  apt:
    name: docker-ce
    update_cache: yes
    state: present
...
