---
- name: Apache
  hosts: all
  tasks:
    - name: Instalar
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Instalar para RedHat
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Copiando o index
      copy:
        src: index.html
        dest: /var/www/html/index.html
     
    - name: Reiniciar o apache
      service:
        name: apache2
        state: restarted
      when: ansible_os_family == "Debian"

    - name: Reiniciar o apache RedHat
      service:
        name: httpd
        state: restarted
      when: ansible_os_family == "RedHat"

...
